module.exports = {
    // WAKE ON LAN
    PHYSICAL_ADDR: '1234',

    // TWITTER KEY
    CONSUMER_KEY: '0wOlHehOvZ3M7OF8XyCrnbBEl',
    CONSUMER_SECRET: 'UKcEm1tSn6DOTVrnCydDOTHloVjP7DNrMGEq5MaFryD3selpvR',
    ACCESS_TOKEN_KEY: '1962083042-c2LkwS1c7VJFR6zMFhHTc9ZzTNicuBNK4RvWKlK',
    ACCESS_TOKEN_SECRET: 'TssKkzwYzHEp75nUf9Uvtobpip03XFEcimWQWQBRcUdmW',
};